export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS = "GET_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const STUDENT_DATA = "STUDENT_DATA";
export const UPDATE_PERMISSION = "UPDATE_PERMISSION";
export const APPROVED_USER = "APPROVED_USER";
export const GET_PROGRAMS = "GET_PROGRAMS";
export const DELETE_USER = "DELETE_USER";
export const GET_USER_DESIGNATIONS = "GET_USER_DESIGNATIONS";

// News and Update
export const GETS_NEWS_UPDATES = "GETS_NEWS_UPDATES";
export const CREATE_NEWS_UPDATES = "CREATE_NEWS_UPDATES";
export const UPDATE_NEWS_UPDATES = "UPDATE_NEWS_UPDATES";
export const DELETE_NEWS_UPDATES = "DELETE_NEWS_UPDATES";
// complaIns
export const GETS_COMPLAINS = "GETS_COMPLAINS";
export const CREATE_COMPLAIN = "CREATE_COMPLAIN";
export const UPDATE_COMPLAIN = "UPDATE_COMPLAIN";
export const DELETE_COMPLAIN = "DELETE_COMPLAIN";
// Offical Documents
export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const CREATE_DOCUMENTS = "CREATE_DOCUMENTS";
export const DELETE_DOCUMENTS = "DELETE_DOCUMENTS";
// Assignment
export const CREATE_ASSIGNMENT = "CREATE_ASSIGNMENT";
export const GET_ASSIGNMENTS = "GET_ASSIGNMENTS";
export const DELETE_ASSIGNMENT = "DELETE_ASSIGNMENT";
export const UPDATE_ASSIGNMENT = "UPDATE_ASSIGNMENT";
// Internship
export const CREATE_INTERNSHIP = "CREATE_INTERNSHIP";
export const GET_INTERNSHIPS = "GET_INTERNSHIPS";
export const UPDATE_INTERNSHIP = "UPDATE_INTERNSHIP";
export const DELETE_INTERNSHIP = "DELETE_INTERNSHIP";

// FYP
export const CREATE_FYP = "CREATE_FYP";
export const GET_FYP = "GET_FYP";
export const DELETE_FYP = "DELETE_FYP";
export const UPDATE_FYP = "UPDATE_FYP";
export const GET_NAMES = "GET_NAMES";
export const UPDATE_FYP_PROJECT = "UPDATE_FYP_PROJECT";
export const CREATE_FYP_CATEGORY = "CREATE_FYP_CATEGORY";
export const GET_FYP_CATEGORY = "GET_FYP_CATEGORY";
export const DELETE_FYP_CATEGORY = "DELETE_FYP_CATEGORY";

// Team
export const GET_TEAMS = "GET_TEAMS";
export const GET_TEAMS_NAMES = "GET_TEAMS_NAMES";
export const CREATE_TEAM = "CREATE_TEAM";
export const ADD_MEMBER = "ADD_MEMBER";
export const GET_MEMBERS = "GET_MEMBERS";
export const ADD_TEAM_ASSIGNMENT = "ADD_TEAM_ASSIGNMENT";
export const DELETE_TEAM = "DELETE_TEAM";
export const GET_TEAM_ASSIGNMENTS = "GET_TEAM_ASSIGNMENTS";
// CSP
export const CREATE_CSP = "CREATE_CSP";
export const GET_CSP = "GET_CSP";
export const DELETE_CSP = "DELETE_CSP";
export const UPDATE_CSP = "UPDATE_CSP";
export const CSP_MEMBERS = "CSP_MEMBERS";
// PEC
export const CREATE_PEC = "CREATE_PEC";
export const GET_PEC = "GET_PEC";
export const DELETE_PEC = "DELETE_PEC";
export const UPDATE_PEC = "UPDATE_PEC";

export const PEC_MEMBERS = "PEC_MEMBERS";

export const CREATE_PEC_DOC_TYPE = "CREATE_PEC_DOC_TYPE";
export const GET_PEC_DOC_TYPE = "GET_PEC_DOC_TYPE";
export const DELETE_PEC_DOC_TYPE = "DELETE_PEC_DOC_TYPE";

// Event
export const CREATE_EVENT = "CREATE_EVENT";
export const GET_PRIVATE_EVENTS = "GET_PRIVATE_EVENTS";
export const GET_PUBLIC_EVENTS = "GET_PUBLIC_EVENTS";
export const DELETE_EVENT = "DELETE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
// slider
export const CREATE_SLIDE = "CREATE_SLIDE";
export const GET_SLIDES = "GET_SLIDES";
export const DELETE_SLIDE = "DELETE_SLIDE";
// quote
export const CREATE_QUOTE = "CREATE_QUOTE";
export const GET_QUOTE = "GET_QUOTE";
export const DELETE_QUOTE = "DELETE_QUOTE";
export const UPDATE_QUOTE = "UPDATE_QUOTE";
// Program
export const CREATE_PROGRAM = "CREATE_PROGRAM";
export const GET_PROGRAMS_ = "GET_PROGRAMS_";
export const DELETE_PROGRAMS = "DELETE_PROGRAMS";
// Batch
export const CREATE_BATCH = "CREATE_BATCH";
export const GET_BATCHS = "GET_BATCHS";
export const DELETE_BATCH = "DELETE_BATCH";

// loadings
//
export const SET_QUOTE_LOADING = "SET_QUOTE_LOADING";
export const CLEAR_QUOTE_LOADING = "CLEAR_QUOTE_LOADING";
//
export const SET_PROGRAM_LOADING = "SET_PROGRAM_LOADING";
export const CLEAR_PROGRAM_LOADING = "CLEAR_PROGRAM_LOADING";

//
export const SET_SLIDER_LOADING = "SET_SLIDER_LOADING";
export const CLEAR_SLIDER_LOADING = "CLEAR_SLIDER_LOADING";

//
export const SET_EVENT_LOADING = "SET_EVENT_LOADING";
export const CLEAR_EVENT_LOADING = "CLEAR_EVENT_LOADING";
//
export const CLEAR_USER_LOADING = "CLEAR_USER_LOADING";
export const SET_USER_LOADING = "SET_USER_LOADING";
//
export const CLEAR_NEWS_LOADING = "CLEAR_NEWS_LOADING";
export const SET_NEWS_LOADING = "SET_NEWS_LOADING";
//
export const SET_COMPLAIN_LOADING = "SET_COMPLAIN_LOADING";
export const CLEAR_COMPLAIN_LOADING = "CLEAR_COMPLAIN_LOADING";
//
export const CLEAR_DOCUMENT_LOADING = "CLEAR_DOCUMENT_LOADING";
export const SET_DOCUMENT_LOADING = "SET_DOCUMENT_LOADING";
//
export const SET_ASSIGNMENT_LOADING = "SET_ASSIGNMENT_LOADING";
export const CLEAR_ASSIGNMENT_LOADING = "CLEAR_ASSIGNMENT_LOADING";
//
export const SET_FYP_LOADING = "SET_FYP_LOADING";
export const CLEAR_FYP_LOADING = "CLEAR_FYP_LOADING";
//
export const SET_TEAM_LOADING = "SET_TEAM_LOADING";
export const CLEAR_TEAM_LOADING = "CLEAR_TEAM_LOADING";
//
export const CLEAR_INTERNSHIP_LOADING = "CLEAR_INTERNSHIP_LOADING";
export const SET_INTERNSHIP_LOADING = "SET_INTERNSHIP_LOADING";
//
export const SET_CSP_LOADING = "SET_CSP_LOADING";
export const CLEAR_CSP_LOADING = "CLEAR_CSP_LOADING";
//
export const CLEAR_PEC_LOADING = "CLEAR_PEC_LOADING";
export const SET_PEC_LOADING = "SET_PEC_LOADING";
